services:
  ffmpeg-cpu:
    build: 
      context: .
      target: cpu-final
      args:
        - FFMPEG_VARIANT=cpu
    env_file: ./.env
    volumes:
      - ./data:/data
    environment:
      - LOG_LEVEL=info
      - LOG_DESTINATION=/data/logs
      - SOURCE_DIRECTORY_PATH=/data/input
      - DESTINATION_DIRECTORY_PATH=/data/output

  ffmpeg-gpu:
    build: 
      context: .
      target: gpu-final
      args:
        - FFMPEG_VARIANT=gpu
    env_file: ./.env
    volumes:
      - ./data:/data
    environment:
      - LOG_LEVEL=info
      - LOG_DESTINATION=/data/logs
      - SOURCE_DIRECTORY_PATH=/data/input
      - DESTINATION_DIRECTORY_PATH=/data/output
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia