version: "3.9"
services:
  ffmpeg:
    build: .
    env_file: ./.env
    volumes:
      - ./data:/data
    environment:
      - LOG_LEVEL=info
      - LOG_DESTINATION=/data/logs
      - SOURCE_DIRECTORY_PATH=/data/input
      - DESTINATION_DIRECTORY_PATH=/data/output
      - FFMPEG_PATH=/usr/bin/ffmpeg